// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc2SY_tyy0pTy13x2QbwXJzHZ_0Lh-DC0',
    appId: '1:829637652319:web:7bf593df96e7de0fe290ea',
    messagingSenderId: '829637652319',
    projectId: 'food-ordering-app-c813f',
    authDomain: 'food-ordering-app-c813f.firebaseapp.com',
    storageBucket: 'food-ordering-app-c813f.appspot.com',
    measurementId: 'G-EH6LMZ5CL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDXMj-KmF_jFgThydgh16dJ2P4p560wOU',
    appId: '1:829637652319:android:637d9db7496e64eee290ea',
    messagingSenderId: '829637652319',
    projectId: 'food-ordering-app-c813f',
    storageBucket: 'food-ordering-app-c813f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvSYDrgNhUPsRKkWYd9bObj7pr7w9NRe0',
    appId: '1:829637652319:ios:fa5323fd8edff50be290ea',
    messagingSenderId: '829637652319',
    projectId: 'food-ordering-app-c813f',
    storageBucket: 'food-ordering-app-c813f.appspot.com',
    iosBundleId: 'com.example.foodOrderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvSYDrgNhUPsRKkWYd9bObj7pr7w9NRe0',
    appId: '1:829637652319:ios:f94b3bf74a718fc1e290ea',
    messagingSenderId: '829637652319',
    projectId: 'food-ordering-app-c813f',
    storageBucket: 'food-ordering-app-c813f.appspot.com',
    iosBundleId: 'com.example.foodOrderingApp.RunnerTests',
  );
}
